site_name: ZoomQuiet.io
site_description: å¤§å¦ˆçš„ä¸»é¡µ
site_author: ZoomQuiet
site_url: https://zoomquiet.io
repo_url: https://github.com/ZoomQuiet/io
repo_name: ZoomQuiet/io
edit_uri: edit/main/docs/
copyright: Copyright 1974-2025 Zoom.Quiet, All rights reserved
theme:
  name: material
  language: zh
  custom_dir: _theme/material
  palette:
    scheme: default
    primary: blue grey
  features:
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant.progress
  - navigation.tracking
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
plugins:
- git-authors
- rss
- search:
    lang: zh
    jieba_dict: ./jieba_dict.small.txt
markdown_extensions:
- toc:
    toc_depth: '3'
    permalink: true
nav:
- é¦–é¡µ: index.md
- èŸ’è¥Â®:
  - 101camp/index.md
  - 'NC: å—¯å“¼èŸ’è¥':
    - 101camp/NC/index.md
    - NC0:ä¸€ä¸ªè‡ªæ¯å€¾å‘ç¤¾åŒºçš„å½¢æˆ: 101camp/NC/20190711-NC101-self-destruction.md
- å¤§å¦ˆ:
  - About/index.md
  - é“¾æ¥: About/20241028-linking.md
  - å…³äº: About/20241015-zoomquiet.md
  - å‹é“¾: About/20200305-friendly-links.md
  - å¸¦è´§: About/20200214-affiliate.md
  - è®¾è®¡: About/20131219-design.md
  - ä½ å¥½ä¸–ç•Œ: About/20130809-hello-world.md
- æ‹™è§:
  - IMHO/index.md
  - DevOps:
    - IMHO/DevOps/index.md
    - å«‘è½¬è¡Œ..: IMHO/DevOps/20241220-devrel.md
    - é»˜é»˜é€€ç¾¤..: IMHO/DevOps/20241129-devrel.md
    - é£Ÿå ‚ç›‘å¯Ÿ?: IMHO/DevOps/20241107-watchdogfood.md
    - å¦‚ä½•åˆ é™¤ Lark èµ„æº?: IMHO/DevOps/20241009-deLark.md
  - è‡ªç”±å¼€æº:
    - IMHO/FLOSS/index.md
    - AIæ—¶ä»£çš„ä¸ªäººå“ç‰Œ: IMHO/FLOSS/20250904-aiage-person-band.md
    - ä¸­å›½å¼€æºç¤¾åŒºæœ€å¤§çš„å¨èƒ: IMHO/FLOSS/20250423-oss-cn-bigger-problem.md
    - ä¼ä¸šçŸ¥è¯†ç®¡ç†?: IMHO/FLOSS/20241114-ekm-problem.md
    - å…³ ä¹ç¤¾ç¾¤:20 æµ…æç¤¾åŒºéœ€è¦ä»€ä¹ˆ?: IMHO/FLOSS/20141215-ac20-need-what.md
    - å…³ ä¹ç¤¾ç¾¤:1024 ä¸­å›½æŠ€æœ¯ç¤¾åŒºç ”ç©¶: IMHO/FLOSS/20140317-ac1024-tech-community4chinese.md
    - å…³ ä¹ç¤¾ç¾¤:2 ä»€ä¹ˆæ˜¯æŠ€æœ¯ç¤¾åŒº?: IMHO/FLOSS/20140227-ac2-tech-community.md
    - å…³ ä¹ç¤¾ç¾¤:1 ä»€ä¹ˆæ˜¯ç¤¾åŒº?: IMHO/FLOSS/20140220-ac1-zq.md
    - wiki ä¸æ˜¯ä»»ä½•äººéƒ½å¯ä»¥ç”¨çš„!: IMHO/FLOSS/20101026-dont-use-wiki.md
  - ç¡åæ”¶å…¥:
    - IMHO/IAS/index.md
    - ä½•ä¸ºè‡ªä¸»ä»¥åŠä½•ä»¥è‡ªä¸»: IMHO/IAS/20241203-how2freedom.md
    - æœªæ¥ç»å¯¹ä»·å€¼æ˜¯ä»€ä¹ˆ?: IMHO/IAS/20241129-future-need.md
    - memeCOIN+DAO?: IMHO/IAS/20241125-memecoin-dao.md
    - ä»€ä¹ˆæ˜¯å†™ä½œ?: IMHO/IAS/20241028-iff-write.md
    - å¼€æºä¿é™©ç¤¾åŒº...: IMHO/IAS/20241026-jy-framwork.md
    - UBNT+Cloudflared: IMHO/IAS/20240918-ubnt-cloudflared.md
    - æ‹™è§/ ç§‘å­¦'æ‘¸é±¼'æŒ‡åŒ—+1: IMHO/IAS/20200221-DM31-IMHO-how2work-deep.md
    - æ‹™è§/ ç§‘å­¦'æ‘¸é±¼'æŒ‡åŒ—+2: IMHO/IAS/20200221-DM32-IMHO-how2work-debug.md
    - ç§‘å­¦'æ‘¸é±¼'æŒ‡åŒ—: IMHO/IAS/20200220-DM30-IMHO-how2work-dark.md
  - ã€Šæˆ‘è¿™æ ·ç”¨GenAIã€‹: IMHO/20240717-aigcxzh-genai102.md
  - æ™®é€šäººæ—¥å¸¸å¦‚ä½•å…è´¹ä½¿ç”¨ GenAI æ¥æ”¹å–„æ¢ç´¢?: IMHO/20240704-aigcxzh-genai101.md
  - æ¢è®¨ ä¿¡æ¯åŒ–ç¤¾ä¼šä¸­ ä¸­å›½ä¼ ç»Ÿæ€æƒ³çš„ä½œç”¨: IMHO/19980101-chinese4internet.md
- å‘¢å–ƒ:
  - MurMur/index.md
  - å‘¢å–ƒ@2025:
    - MurMur/25/index.md
    - å’©æ˜¯ Vibe coding çš„ vibe?: MurMur/25/20250905-vibe101coding.md
    - çŸ¥è¯†ä»˜è´¹å’Œ vibe building: MurMur/25/20250903-vibe-anything.md
    - å’©`æ¶æ„æ„Ÿ`å—¦..: MurMur/25/20250721-IMHO.md
    - AI ç‰›é©¬å¿ƒç†å­¦?: MurMur/25/20250620-cc.md
    - '|> 250510 æ—¥ç³Ÿ:': MurMur/25/20250510-1.md
    - ç…®é¢å®šå¾‹: MurMur/25/20250508.md
    - å¹¿ä¹‰å¸ƒé“è€…: MurMur/25/20250502-2.md
    - ä¹¦çš„æœªæ¥ï¼šé‡å®šä¹‰ä¸å†æƒ³è±¡: MurMur/25/20250424.md
    - LLMæ—¶ä»£å·¥ç¨‹å¸ˆé€‰å‹..: MurMur/25/20250423.md
    - LLMçœŸæé«˜äº†ç¨‹åºå‘˜çš„æ•ˆç‡å—ï¼Ÿ: MurMur/25/20250312.md
  - å‘¢å–ƒ@2024:
    - MurMur/24/index.md
    - ç”Ÿå‘½æ—¶é—´çš„é€Ÿç‡?: MurMur/24/20241219.md
    - '"æªåŒ…"ä»¥åŠèƒŒå¸¦çš„è¿›åŒ–': MurMur/24/20241215.md
    - '|> 241112 æ—¥ç³Ÿ:': MurMur/24/20241112.md
    - '|> 241112 æ—¥ç³Ÿ:': MurMur/24/20241112-1.md
    - '|> 241109 æ—¥ç³Ÿ:': MurMur/24/20241109.md
    - '> 241107 æ—¥ç³Ÿ:': MurMur/24/20241107.md
    - '|> 241028 æ—¥ç³Ÿ:': MurMur/24/20241028.md
    - æ·±æŒ–å¼€æºçš„ç¤¾ä¼šä»·å€¼ä¸ç»æµè§„å¾‹: MurMur/24/20241024.md
    - '|> 241023 æ—¥ç³Ÿ:': MurMur/24/20241023.md
    - GOAT çš„æ•…äº‹: MurMur/24/20241020.md
    - '|> 241014 æ—¥ç³Ÿ:': MurMur/24/20241014.md
    - '|> 240929 æ—¥ç³Ÿ:': MurMur/24/20240929.md
    - '|> 240924 æ—¥ç³Ÿ:': MurMur/24/20240924.md
    - '|> 240914 æ—¥ç³Ÿ:': MurMur/24/20240914.md
    - '|> 240912 æ—¥ç³Ÿ:': MurMur/24/20240912.md
    - '|> 240911 æ—¥ç³Ÿ:': MurMur/24/20240911.md
    - '|> 240905 æ—¥ç³Ÿ:': MurMur/24/20240904.md
    - '"æªåŒ…"ä»¥åŠèƒŒå¸¦çš„è¿›åŒ–': MurMur/24/20240903.md
    - '|> 240730 æ™¨ç³Ÿ:': MurMur/24/20240730.md
    - '|> 240727 æ™©å®‰:': MurMur/24/20240727.md
    - '|> 240725 æ™¨ç³Ÿ:': MurMur/24/20240725.md
    - å¼€æºå®‰å…¨AI?: MurMur/24/20240723+1.md
    - å’Œé«˜æ‰‹çš„å·®è·: MurMur/24/20240723.md
    - '|> è°æ‹¥æœ‰å¸‚åœº, è°å°±æ‹¥æœ‰æ™ºæ…§:': MurMur/24/20240722.md
    - '|> 240718 æ™©å®‰:': MurMur/24/20240718.md
    - '|> 240717 æ™¨ç³Ÿ': MurMur/24/20240717.md
    - '|> 240717 æ™¨ç³Ÿ+1': MurMur/24/20240717-1.md
  - å‘¢å–ƒ@2016:
    - MurMur/16/index.md
    - '[0/N] è®ºå¾—è¶£': MurMur/16/160927-justfun-0.md
    - '[1/N] è®ºå¾—è¶£': MurMur/16/160928-justfun-1.md
    - '[2/N] è®ºå¾—è¶£': MurMur/16/160929-justfun-2.md
    - '[3/N] è®ºå¾—è¶£': MurMur/16/160930-justfun-3.md
    - '[4/N] è®ºå¾—è¶£': MurMur/16/161008-justfun-4.md
    - '[5/N] è®ºå¾—è¶£': MurMur/16/161009-justfun-5.md
  - KnewOne-talk ä¹‹ å¤§å¦ˆ ç¯‡: MurMur/20141223-zoomquiet4KO.md
  - '"CIPHER"': MurMur/19961111-CIPHER.md
- é’©é™ˆ:
  - OldTouch/index.md
  - é’©é™ˆ2024:
    - OldTouch/24/index.md
    - å›ç­”ä½ è¿™ 9 ä¸ªé—®é¢˜..: OldTouch/24/20241110-echo9dayu.md
    - å‹å¥½çš„æ³•é™¢?: OldTouch/24/20241011-funny-court.md
  - é€šå‘Š:
    - OldTouch/ANN/index.md
    - Follow è®¢é˜…æº: OldTouch/ANN/20250407-ANN-follow.md
    - å…¬å‘Š/ å‘¢å–ƒ: OldTouch/ANN/20200302-ZQ42-ANN-NINAN.md
    - å…¬å‘Š/ å•é‡æ–°å¼€å§‹çš„å¤§å¦ˆ: OldTouch/ANN/20200223-ZoomQuiet42-ANN-0-aaaagin.md
    - å…¬å‘Š/ æ‹™è§: OldTouch/ANN/20200222-ZQ42-ANN-IMHO.md
    - å…¬å‘Š/ é’©é™ˆ: OldTouch/ANN/20200222-ZQ42-ANN-historic.md
    - PRESSone: OldTouch/ANN/20170910-pressone.md
  - å¥½ä¸­æ–‡:
    - OldTouch/GC4WP/index.md
    - '[S03E23] æˆ‘çš„äººç”Ÿä¸ƒå¹´': OldTouch/GC4WP/20190712-GC4-S03E23-42UP.md
    - L10E01ğŸ™GPL: OldTouch/GC4WP/20180204-L10E01GPL.md
    - L06E01ğŸ™ĞĞ½Ğ½Ğ° ĞšĞ°Ñ€ĞµĞ½Ğ¸Ğ½Ğ°: OldTouch/GC4WP/20180104-L06E01ĞĞ½Ğ½Ğ°-ĞšĞ°Ñ€ĞµĞ½Ğ¸Ğ½Ğ°.md
    - L04E51ğŸ™é•¿åŸç®€å²: OldTouch/GC4WP/20171231-L04E51greatwall.md
    - GC4L02E05ğŸ™æ±‰è¯­å¼•è¿›çš„: OldTouch/GC4WP/20171212-GC4L02E05chinese-imports.md
    - GC4S18E1sğŸ™ æ€æ ·ç”¨ç§»åŠ¨æ”¯ä»˜é€šè¿‡é«˜é“åœ¨ä¸€å¤©å†…å°éä¸­å›½ç¾é£Ÿ: OldTouch/GC4WP/20170607-GC4S18E1s.md
    - GC4S16E51ğŸ™ CPHB: OldTouch/GC4WP/20170523-GC4S16E51CPHB.md
    - GC4S15E51ğŸ™ è‰¯äºº: OldTouch/GC4WP/20170521-GC4S15E51goodman.md
    - GC4S14E51ğŸ™ çœŸå®çš„å¦‚åŒå‡è£…: OldTouch/GC4WP/20170512-GC4S14E51true4frake.md
    - 'S13E15: ä¸€ç”Ÿæ‰€æ±‚': OldTouch/GC4WP/20170421-S13E15-fullifeask.md
    - 'S11E01: æµ·æ¸¯ ç«‹å…¶è¯š': OldTouch/GC4WP/20170411-S11E01.md
    - 'S10E15: å¸å•åºŸç¨¿': OldTouch/GC4WP/20170408-S10E15.md
    - 'S02E01: å‘¨ç”Ÿå‰§æœ¬å¤§çº²': OldTouch/GC4WP/20170401-S02E01-GC4script.md
    - è‡ªç”±é—®è‡ªç–: OldTouch/GC4WP/20170328-S09E05gDAMA-ask-freedom.md
    - S09E05gDAMA:è‡ªç”±é—®: OldTouch/GC4WP/20170327-S09E05gDAMA.md
    - 'S07E15g193: å—¯å“¼é‡æ¥': OldTouch/GC4WP/20170314-S07E15g193-re-hummm.md
    - 'S07E15g193: å’ŒåˆæŠ€ ç§ä¾‹': OldTouch/GC4WP/20170314-S07E15g193-examples.md
    - 'S06E05g56: å·´åˆ«å¡”': OldTouch/GC4WP/20170306-S06E05g56-babel-tower.md
    - 'S06E05g56: å†æ¬¡å—¯å“¼': OldTouch/GC4WP/20170305-S06E05g56-re-humm.md
    - 'S06E05g56: åºŸç¨¿': OldTouch/GC4WP/20170305-S06E05g56-babel-tower-draft.md
    - 'S03E05g56: 3é¡µA4çº¸ éš¾ä»¥å¤±è´¥çš„è›‹ç‚’é¥­æ•™ç¨‹': OldTouch/GC4WP/20170211-S03E05g56-rise-file-eeg.md
    - 'GC4g56: å’ŒåˆæŠ€~å¼ºé‡Š': OldTouch/GC4WP/20170211-GC4g56-define-mergging.md
    - GC4S03E05g56:å—¯å“¼ å¤ç›˜: OldTouch/GC4WP/20170210-GC4S03E05g56-review.md
    - GC4S01E03:ä¿ºæ˜¯å¹²å˜›çš„?!: OldTouch/GC4WP/20170115-GC4S01E03-what-i-do-for.md
    - 'GC4S01E01: æˆ‘çš„è¾©æŠ¤': OldTouch/GC4WP/20170112-GC4S01E01.md
  - ä¹ƒæœ¨å‚46:
    - OldTouch/NGZK46/index.md
    - ç´«â˜†S5: OldTouch/NGZK46/20250510-nnnewstar.md
  - ç§‘å¹»:
    - OldTouch/SiFi/index.md
    - L10E01ğŸ™çº¢é»„è“ ~ è™ç«¥æˆ˜çºª: OldTouch/SiFi/20180501-L10E01-ryb-wars.md
    - L03E01ğŸ™ä»å‰æ˜¯ç°åœ¨: OldTouch/SiFi/20171222-L03E01-passisnow.md
    - GC4L01E01ğŸ™ä»å‰çš„ç°åœ¨: OldTouch/SiFi/20171201-GC4L01E01-now-from-past.md
    - GC4S19E51ğŸ™ as the writer: OldTouch/SiFi/20170613-GC4S19E51-as-wirter.md
    - S12E01:23ä¸–çºª:å­¦æ ¡: OldTouch/SiFi/20170418-S12E01-23cc.md
    - 'S05E01: A,Eå’ŒS': OldTouch/SiFi/20170223-S05E01-a-e-s.md
    - 'S04E15: æ— ä¹‹è¯—ç¯‡23': OldTouch/SiFi/20170214-S04E15-poem23.md
    - é­”æ˜Ÿ  Magic star: OldTouch/SiFi/20170123-2002-magic-star.md
    - Dream World: OldTouch/SiFi/20150615-99-dream-world.md
  - é’©é™ˆ/ æ¸©æ€»çš„è¯­é€Ÿ...: OldTouch/20210807-OldTouch-APISIX.md
  - é’©é™ˆ/ ä»€ä¹ˆæ˜¯ç¨‹åºåª›?: OldTouch/20200304-ZoomQuiet-OldTouch-380.md
  - é’©é™ˆ/ CPUGæ•…äº‹: OldTouch/20200226-ZoomQuiet-OldTouch-CPUG.md
  - é’©é™ˆ/ æ è¿‡ æ–‡åŒ–ç¤¾åŒº: OldTouch/20200225-ZoomQuiet-OldTouch-booking.md
  - æ‹™è§/ å››å¤„ ç®´è¨€æ–­å–: OldTouch/20200225-ZoomQuiet-OldTouch-DebugUself.md
  - é’©é™ˆ/ å¸ƒé“ æŠ€æœ¯ç¤¾åŒº: OldTouch/20200225-ZoomQuiet-OldTouch-tech.md
  - é’©é™ˆ/ æ›¾ç» æœ‰å…³ç¤¾åŒº: OldTouch/20200225-ZoomQuiet-OldTouch-abt.md
  - å¦‚ä½•ä» Jekyll è½¬è¿›å…¥ Pelican: OldTouch/20131219-jekyll2pelican.md
- Pythonic:
  - Pythonic/index.md
  - èŸ’æ ·@2025:
    - Pythonic/25/index.md
    - å¦‚ä½•æ„å»ºå…¨ AI èŠ¯ç‰‡è®¾è®¡å…¬å¸?: Pythonic/25/20250629-ai-chip-design-feasibility-report.md
    - CC ä¸­çš„ gh-issue å·¥ä½œæµ: Pythonic/25/20250615-claude-code-gh-flow.md
    - æ€ç»´å›¾è°±çŸ¢é‡åŒ–: Pythonic/25/20250510-graphivz-svg.md
  - èŸ’æ ·@2024:
    - Pythonic/24/index.md
    - PJ.MIAOLAI D2: Pythonic/24/20241111-pj-miaolai-d2.md
    - æˆªå±å†²çªè§£å†³: Pythonic/24/20241107-mac-snap-lunar.md
    - Garage ä½œç§äºº S3 æœåŠ¡: Pythonic/24/20241029-intra-s3-garage.md
    - è‡ªæŒå›¾åºŠ: Pythonic/24/20241028-loc-host-s3.md
    - å¦‚ä½•ç»™ mdBook æŒ‚ä¸Š RSS?: Pythonic/24/20241016-rss4mdbook.md
    - å¤è€çš„ dvd_subtitle: Pythonic/24/20241016-dvd_subtitle.md
    - å¦‚ä½•ç»™Xç”ŸæˆRSS: Pythonic/24/20241015-rss-app-x.md
    - è¿ç§» gh-pages åˆ° Cloudflare: Pythonic/24/20241014-cf-pages.md
    - ç”µå½±ä¸­æ–‡å­—å¹•?: Pythonic/24/20241011-mov-sub.md
    - 9.18 UBNT+Cloudflared: Pythonic/24/20240918-ubnt-cloudflared.md
    - ç¨‹åºçŒ¿AIGC"å·¥å…·åŒ…": Pythonic/24/20240123-aigc-x-zhuhai-toolkit4developer.md
  - Python ä¸­çš„å­—å…¸è°ƒåº¦æ¨¡å¼: Pythonic/20230209-dict-dispatch-pattern-in-python .md
  - ScrapBook åœ¨ M1macOS ä¸Šæ¢å¤: Pythonic/20221213-scrapbook-revert.md
  - å¦‚ä½•å®‰å®šè¿›å…¥ M1maxMBP: Pythonic/20211114-M1max-re-inti-MBP.md
  - VNCå›å½’è½»æ¾: Pythonic/20200704-easy-vnc.md
  - æ‹™è§/ DNSä¹‹æ®‡: Pythonic/20200331-ZoomQuiet-MurMur-dnsad.md
  - é’©é™ˆ/ è¢«jianshuè®¤è¯äº†: Pythonic/20200227-ZoomQuiet-OldTouch-jianshu.md
  - Elixir ä¸­åˆ—å‡º Map ä¸­å€¼é”®å¯¹çš„æŠ˜è…¾...: Pythonic/20200108-ex-map-enum.md
  - ç”¨ DSL ä»¬æ„ç­‘å•†ç”¨ç³»ç»Ÿ: Pythonic/20170827-DSLs-atop-openrety.md
  - å¦‚ä½•å°† ipynb å‘å¸ƒåˆ° blog ä¸­?: Pythonic/20141127-ipynb-into-blog.md
  - åå¤§æ—©è¯¥çŸ¥é“çš„PythonæŠ€å·§: Pythonic/20141126-top10-Py-idioms-wish-learned-earlier.md
  - å¦‚ä½•è‡ªåœ¨çš„æŠ˜è…¾QPy: Pythonic/20140126-inti-my-qpy-env.md
  - Python åˆ—è¡¨ä¸ºæ¯›ä»0å¼€å§‹ç´¢å¼•?: Pythonic/20131023-why0base-indexing-python.md
- å‘¨åˆŠ:
  - Weekly/index.md
  - 2025 èŸ’å‘¨åˆŠ:
    - Weekly/25/index.md
    - 'ä¸Šå‘¨è å¿«è®¯ #706': Weekly/25/20251029-706.md
    - 'ä¸Šå‘¨è å¿«è®¯ #705': Weekly/25/20251022-705.md
    - 'ä¸Šå‘¨è å¿«è®¯ #704': Weekly/25/20251015-704.md
    - 'ä¸Šå‘¨è å¿«è®¯ #703': Weekly/25/20251007-703.md
    - 'ä¸Šå‘¨è å¿«è®¯ #702': Weekly/25/20251001-702.md
    - 'ä¸Šå‘¨è å¿«è®¯ #701': Weekly/25/20250924-701.md
    - 'ä¸Šå‘¨è å¿«è®¯ #700': Weekly/25/20250917-700.md
    - 'ä¸Šå‘¨è å¿«è®¯ #699': Weekly/25/20250917-699.md
    - 'ä¸Šå‘¨è å¿«è®¯ #698': Weekly/25/20250910-698.md
    - 'ä¸Šå‘¨è å¿«è®¯ #697': Weekly/25/20250903-697.md
    - 'ä¸Šå‘¨è å¿«è®¯ #696': Weekly/25/20250827-696.md
    - 'ä¸Šå‘¨è å¿«è®¯ #695': Weekly/25/20250820-695.md
    - 'ä¸Šå‘¨è å¿«è®¯ #694': Weekly/25/20250813-694.md
    - 'ä¸Šå‘¨è å¿«è®¯ #693': Weekly/25/20250806-693.md
    - 'ä¸Šå‘¨è å¿«è®¯ #692': Weekly/25/20250730-692.md
    - 'ä¸Šå‘¨è å¿«è®¯ #691': Weekly/25/20250723-691.md
    - 'ä¸Šå‘¨è å¿«è®¯ #690': Weekly/25/20250716-690.md
    - 'ä¸Šå‘¨è å¿«è®¯ #689': Weekly/25/20250709-689.md
    - 'ä¸Šå‘¨è å¿«è®¯ #688': Weekly/25/20250701-688.md
    - 'ä¸Šå‘¨è å¿«è®¯ #687': Weekly/25/20250625-687.md
    - 'ä¸Šå‘¨è å¿«è®¯ #686': Weekly/25/20250618-686.md
    - 'ä¸Šå‘¨è å¿«è®¯ #685': Weekly/25/20250611-685.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/22: Weekly/25/20250605-22.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/21: Weekly/25/20250526-21.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/20: Weekly/25/20250519-20.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/19: Weekly/25/20250512-19.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/18: Weekly/25/20250505-18.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/17: Weekly/25/20250428-17.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/16: Weekly/25/20250421-16.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/15: Weekly/25/20250414-15.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/14: Weekly/25/20250407-14.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/13: Weekly/25/20250331-13.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/12: Weekly/25/20250324-12.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/11: Weekly/25/20250317-11.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/10: Weekly/25/20250310-10.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/09: Weekly/25/20250303-09.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/08: Weekly/25/20250224-08.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/07: Weekly/25/20250217-07.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/06: Weekly/25/20250210-06.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/05: Weekly/25/20250202-05.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/04: Weekly/25/20250127-04.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/03: Weekly/25/20250120-03.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/02: Weekly/25/20250113-02.md
    - ä¸Šå‘¨è å¿«è®¯ 2025/01: Weekly/25/20250106-01.md
  - 2024 èŸ’å‘¨åˆŠ:
    - Weekly/24/index.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/52: Weekly/24/20241230-52.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/51: Weekly/24/20241223-51.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/50: Weekly/24/20241216-50.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/49: Weekly/24/20241209-49.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/48: Weekly/24/20241202-48.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/47: Weekly/24/20241125-47.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/46: Weekly/24/20241118-46.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/45: Weekly/24/20241111-45.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/43: Weekly/24/20241028-43.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/44: Weekly/24/20241028-44.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/42: Weekly/24/20241020-42.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/41: Weekly/24/20241014-41.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/40: Weekly/24/20241006-40.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/39: Weekly/24/20240929-39.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/38: Weekly/24/20240922-38.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/37: Weekly/24/20240915-37.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/36: Weekly/24/20240908-36.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/35: Weekly/24/20240901-35.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/34: Weekly/24/20240825-34.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/33: Weekly/24/20240818-33.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/32: Weekly/24/20240811-32.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/31: Weekly/24/20240804-31.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/30: Weekly/24/20240728-30.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/29: Weekly/24/20240721-29.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/28: Weekly/24/20240714-28.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/27: Weekly/24/20240707-27.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/26: Weekly/24/20240630-26.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/25: Weekly/24/20240623-25.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/24: Weekly/24/20240616-24.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/23: Weekly/24/20240609-23.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/22: Weekly/24/20240602-22.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/21: Weekly/24/20240526-21.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/20: Weekly/24/20240519-20.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/19: Weekly/24/20240512-19.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/18: Weekly/24/20240505-18.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/17: Weekly/24/20240428-17.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/16: Weekly/24/20240421-16.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/15: Weekly/24/20240414-15.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/14: Weekly/24/20240407-14.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/13: Weekly/24/20240331-13.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/12: Weekly/24/20240324-12.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/11: Weekly/24/20240317-11.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/10: Weekly/24/20240310-10.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/9: Weekly/24/20240303-09.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/8: Weekly/24/20240225-08.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/7: Weekly/24/20240218-07.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/6: Weekly/24/20240211-06.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/5: Weekly/24/20240204-05.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/4: Weekly/24/20240128-04.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/3: Weekly/24/20240121-03.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/2: Weekly/24/20240114-02.md
    - ä¸Šå‘¨è å¿«è®¯ 2024/1: Weekly/24/20240107-01.md
